version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - "Robert-96"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "Robert-96"
    schedule:
      interval: "weekly"
