repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: unit-tests
        name: Run Unit Tests
        language: system
        entry: npm test
        files: ^(themes|tests|content)/.*$
        pass_filenames: false
