repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-case-conflict

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
    -   id: gitleaks
