baseURL = "http://www.dezmereanrobert.com/"
title = "Dezmerean Robert"
theme = "loaf"
languageCode = "en"

[params]
  author = "Dezmerean Robert"
  title = "Dezmerean Robert"
  description = "Dezmerean Robert's boring personal website."
  images = ['site-feature-image.jpg']

[social]
  twitter = "dezmereanrobert"
  github = "Robert-96"
  linkedin = "robert-dezmerean"

[taxonomies]
  tag = 'tags'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 100

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 110

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 120

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 130
